version: 2.1

jobs:
  snyk_scan:
    docker:
      - image: cimg/node:18.19
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: npm install

      - run:
          name: Install Snyk
          command: npm install -g snyk

      - run:
          name: Authenticate Snyk
          command: snyk auth $SNYK_TOKEN

      - run:
          name: Snyk Open Source Scan
          command: snyk test --all-projects

      - run:
          name: Snyk Code Scan
          command: snyk code test
workflows:
  version: 2
  snyk_workflow:
    jobs:
      - snyk_scan:
          filters:
            branches:
              only:
                - main
                - master
